version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:213.0.0
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
